FROM php:8.3-alpine

RUN apk add $PHPIZE_DEPS && pecl install redis

RUN apk add $PHPIZE_DEPS
COPY scripts/docker-php-ext-active /usr/local/bin/docker-php-ext-active
RUN chmod +x /usr/local/bin/docker-php-ext-active

RUN docker-php-ext-enable redis && \
    docker-php-ext-active redis
