FROM php:8.4-alpine

RUN apk add --no-cache $PHPIZE_DEPS

COPY scripts/docker-php-ext-active /usr/local/bin/docker-php-ext-active
RUN chmod +x /usr/local/bin/docker-php-ext-active

RUN docker-php-ext-install -j$(nproc) calendar && \
    docker-php-ext-active calendar
