FROM php:8.3-alpine

RUN apk add --no-cache $PHPIZE_DEPS imagemagick-dev

ENV LDFLAGS="-Wl,-rpath,/opt/php/lib"

RUN pecl install imagick

COPY scripts/docker-php-ext-active /usr/local/bin/docker-php-ext-active
RUN chmod +x /usr/local/bin/docker-php-ext-active

RUN docker-php-ext-enable imagick && \
    docker-php-ext-active imagick
