FROM php:8.0-alpine

RUN apk add $PHPIZE_DEPS
COPY scripts/docker-php-ext-active /usr/local/bin/docker-php-ext-active
RUN chmod +x /usr/local/bin/docker-php-ext-active

RUN docker-php-ext-enable opcache && \
    docker-php-ext-active opcache
