FROM php:8.2-alpine

RUN apk add --no-cache postgresql-dev

ENV LDFLAGS="-Wl,-rpath,/opt/php/lib"

RUN apk add $PHPIZE_DEPS
COPY scripts/docker-php-ext-active /usr/local/bin/docker-php-ext-active
RUN chmod +x /usr/local/bin/docker-php-ext-active

ENV LDFLAGS="-Wl,-rpath,/opt/php/lib"

RUN docker-php-ext-install pdo_pgsql && \
    docker-php-ext-active pdo_pgsql
