FROM php:8.1-alpine

RUN apk add --no-cache $PHPIZE_DEPS

ENV LDFLAGS="-Wl,-rpath,/opt/php/lib"

RUN pecl install msgpack

COPY scripts/docker-php-ext-active /usr/local/bin/docker-php-ext-active
RUN chmod +x /usr/local/bin/docker-php-ext-active

RUN docker-php-ext-enable msgpack && \
    docker-php-ext-active msgpack
