FROM php:8.1-alpine

RUN apk add --no-cache gettext-dev

ENV LDFLAGS="-Wl,-rpath,/opt/php/lib"

RUN apk add $PHPIZE_DEPS
COPY scripts/docker-php-ext-active /usr/local/bin/docker-php-ext-active
RUN chmod +x /usr/local/bin/docker-php-ext-active

ENV LDFLAGS="-Wl,-rpath,/opt/php/lib"

RUN docker-php-ext-install gettext && \
    docker-php-ext-active gettext
