FROM php:8.2-alpine

RUN apk add --no-cache $PHPIZE_DEPS libmemcached-dev zlib-dev cyrus-sasl-dev

ENV LDFLAGS="-Wl,-rpath,/opt/php/lib"

RUN pecl install memcached

COPY scripts/docker-php-ext-active /usr/local/bin/docker-php-ext-active
RUN chmod +x /usr/local/bin/docker-php-ext-active


RUN docker-php-ext-enable memcached && \
    docker-php-ext-active memcached
