FROM php:8.5-alpine

RUN apk add $PHPIZE_DEPS
COPY scripts/docker-php-ext-active /usr/local/bin/docker-php-ext-active
RUN chmod +x /usr/local/bin/docker-php-ext-active

ENV LDFLAGS="-Wl,-rpath,/opt/php/lib"

RUN docker-php-ext-install mysqli && \
    docker-php-ext-active mysqli
