FROM php:8.2-alpine

RUN apk add --no-cache $PHPIZE_DEPS libxml2-dev

ENV LDFLAGS="-Wl,-rpath,/opt/php/lib"

RUN pecl install xmlrpc-1.0.0RC3

COPY scripts/docker-php-ext-active /usr/local/bin/docker-php-ext-active
RUN chmod +x /usr/local/bin/docker-php-ext-active

RUN docker-php-ext-enable xmlrpc && \
    docker-php-ext-active xmlrpc
