FROM php:8.3-alpine

RUN apk add --no-cache $PHPIZE_DEPS icu-dev

COPY scripts/docker-php-ext-active /usr/local/bin/docker-php-ext-active
RUN chmod +x /usr/local/bin/docker-php-ext-active

ENV LDFLAGS="-Wl,-rpath,/opt/php/lib"

RUN docker-php-ext-install -j$(nproc) intl && \
    docker-php-ext-active intl
