name: Rebuild All

on:
  workflow_dispatch:

jobs:
  rebuild-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        extension: [bcmath, calendar, exif, gd, gettext, gmp, grpc, igbinary, imagick, imap, intl, ldap, memcache, memcached, mongodb, msgpack, mysqli, opcache, pcntl, pcov, pdo_mysql, pdo_pgsql, protobuf, redis, sockets, sodium, uuid, xdebug, xmlrpc, xsl, yaml, zip]
        version: ["8.0", "8.1", "8.2", "8.3", "8.4", "8.5"]
        exclude:
          - extension: opcache
            version: "8.5"
          - extension: imap
            version: "8.4"
          - extension: imap
            version: "8.5"
          - extension: memcache
            version: "8.5"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: dockerphpext
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        with:
          platforms: linux/amd64,linux/arm64

      - name: Build extension image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t dockerphpext/${{ matrix.extension }}:php${{ matrix.version }}-alpine \
            -f extensions/${{ matrix.extension }}/${{ matrix.version }}/Dockerfile.alpine .

      - name: Run tests
        run: |
          make run-single-test extension=${{ matrix.extension }} php_version=${{ matrix.version }}

      - name: Build and Push extension image
        id: build-and-push
        run: |
          FULL_IMAGE_NAME="dockerphpext/${{ matrix.extension }}"
          TAG="php${{ matrix.version }}-alpine"
          docker push "$FULL_IMAGE_NAME:$TAG"
