FROM php:8.3-alpine

RUN apk add --no-cache imap-dev krb5-dev openssl-dev

RUN apk add $PHPIZE_DEPS
COPY scripts/docker-php-ext-active /usr/local/bin/docker-php-ext-active
RUN chmod +x /usr/local/bin/docker-php-ext-active

ENV LDFLAGS="-Wl,-rpath,/opt/php/lib"

RUN docker-php-ext-configure imap --with-kerberos --with-imap-ssl && \
    docker-php-ext-install imap && \
    docker-php-ext-active imap
